### ISSUE TITLE
"Too many selections" errors with BattleScribe v2

### ISSUE THREAD

**Issue by PeterWelzien** [BSData/gates-of-antares#101]
I've just installed the new BattleScribe (v2.00.13 on Android) and I'm trying to create a Freeborn force (Freeborn v6 and Gates of Antares v9 datafiles). I get the following roster errors when I've added a Domari Squad:

5x Household Trooper has 4 too many selections from Ranged Weapon (maximum 1)
Domari Squad (Household Troops) has 1 too many selections from < Unit Armor > (maximum 1)
Domari Squad (Household Troops) has 1 too many selections of Reflex Armor (Eq) (maximum 1 each)

Domari Squad/Household Trooper/Ranged Weapon has min/max 1 Selections in Parent. Can't we just delete those constraints to get rid of the first problem?

Domari Squad contains two "entries", Household Leader and Household Trooper. I guess that's why it complains about too many armours. I tried changing the constraint to max/min 2 Selections in Parent, but that didn't help. Maybe I don't quite understand how constraints work.

**Comment by glasvandrare** [comment]
I've seen the same, but not managed to wrap my head aroudn it yet.

**Comment by clandaith** [comment]
This is no longer an issue with the latest release.
