### ISSUE TITLE
Access Removed?

### ISSUE THREAD

**Issue by clandaith** [BSData/gates-of-antares#123]
So after a long time away, I've started to update the files to the V1 points.  I've completed the Isorian file and went to push it back into the group, but I'm getting a 403 error.  

Has my access been removed?  And if so, can I get it added back?

Thanks.

**Comment by glasvandrare** [comment]
I've not done anything, I'll take a look.

//T

Den 21 aug 2017 17:42 skrev "Troy Davidson" <notifications@github.com>:

**Comment by amis92** [comment]
It does look so, indeed. I've been doing some cleanup and rearranging in Teams, so. Adding you back. Cheers!
