### ISSUE TITLE
Manage repository

### ISSUE THREAD

**Issue by Harkan38** [BSData/gates-of-antares#138]
Hi there, am going to take over the upkeep of the Gates of Antares files, can you give me author access to this please

Thanks

**Comment by amis92** [comment]
@glasvandrare @clandaith @shammond42 Please confirm

**Comment by glasvandrare** [comment]
Confirmed.

fre 29 dec. 2017 kl. 23:31 skrev Amadeusz Sadowski <notifications@github.com

**Comment by shammond42** [comment]
Fine with me.

**Comment by amis92** [comment]
Hello, @Harkan38 . Please accept the invitation in the email or on the [repo webpage](https://github.com/BSData/gates-of-antares/invitations). Welcome aboard!

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

Cheers!
