### ISSUE TITLE
Bug: Algoryn - Liberators not showing initial weapon selections

### ISSUE THREAD

**Issue by Harkan38** [BSData/gates-of-antares#144]
None of the Liberators are showing initial weapon choices selected when chosen

(Will be fixed in next release)

**Comment by Harkan38** [comment]
Fixed in release 1.10

**Comment by glasvandrare** [comment]
Last release was 1.9, shouldn't that meant that this would be fixed in 1.10?

**Comment by Harkan38** [comment]
Yup true!  Corrected

**Comment by Harkan38** [comment]
Done
