### ISSUE TITLE
[Anon] Bug report: Isorian.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/gates-of-antares#148]
**File:** Isorian.catz

**BattleScribe version:** 2.01.14

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** The Isorian category says that there are too many strategic units with a maximum of -3. I have zero strategic units and the database still says my list is inactive

**Comment by TimCoraxAudio** [comment]
This is an easy fix, however there are problems with a few other armies strategic choices being wrong. Will look into this further
