### ISSUE TITLE
Ghar Points On BSData File Are Different from latest Warlord Version 3.0

### ISSUE THREAD

**Issue by scooba13** [BSData/gates-of-antares#159]
The BattleScribe Data File has some points values that are different from the latest Warlord Games version 3.0 file for the Ghar:

- Additional Troopers should be 57 points instead of  60 points in all the units where you can add troopers (this might need a change to the assigned "leader value" so that all the troopers work out at 57 and the base squad value is still 184)
- The points value of the outcast squad should be 42 and the weapon team with disruptor cannon should be 23 (whether as a stand alone unit or an add on to the outcast squad) - BS has them at 43 and 24.
- Tactical Command Squad is a limited choice option at 216 points
- outcast command squad is 38 points instead of 40
- up to 2 additional outcasts with maglash can be added to the command squad for 6 points each (not 4)
- with the outcast squad additional outcasts with lugger guns are 6 pts (not 5) and there is a Vac Armor option at 2pts per model to increase Res to 4(5) at a cost of reducing Ag to 5
- crew for the weapon team are 4 points each (not 12) and adding a leader is 11pts (not 9) 

I haven't checked the suport, strategic and auxillary units yet.  I'm new to Github and programming but willing to learn if there's a way I can help with the editing - let me know if I can help or if you need any further information.

**Comment by TimCoraxAudio** [comment]
This is a pretty easy fix. Thanks for the update, this helps a lot. 

As for helping out, this will be the perfect place for you to start out as these are such easy fixes. Have a look around the web for working with git and battlescribe data editing. Let me know if you need any more help

**Comment by TimCoraxAudio** [comment]
There are 2 related issues with this, all replies should be sent to issue #171 in future
