### ISSUE TITLE
[Anon] Bug report: Isorian.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/gates-of-antares#172]
**File:** Isorian.catz

**BattleScribe version:** 2.01.22

**Platform:** Android

**Dropbox:** No

**Description:** No option for generic Drone Commander

No option for nano probe net (also note that the army must take a drone commander to take one, and it ts a tactical entry)

Pulse bike squad should not have option for synchroniser drone

Heavy Support Team is only listed as “Support Team” under Strategic

Base weapon is listed as an X Launcher, it should be an X Howitzer

Andhak Medium Support Drone needs Phase-Shift Projector added to weapon options (free)

Enhanced Machine Intelligence upgrade for the Tograh Transport Drone should be 10 points and not free

**Comment by TimCoraxAudio** [comment]
The nano probe net is already in BattleScribe. It is under uncategorised as it doesn't count towards the force selector
