### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by clandaith** [BSData/gates-of-antares#21]
I would like to be able to help work with the data files.

**Comment by amis92** [comment]
Please take a look through https://github.com/BSData/bsdata/wiki, and especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

I've sent you an invitation, please accept it to be a member. Cheers!

**Comment by clandaith** [comment]
Already accepted.  

I found the developer guide last night after I made a pull request.  I cancelled that one out.  I also found the part about not committing zipped files.

Thanks for the add.

**Comment by amis92** [comment]
Great, cheers :)

**Comment by glasvandrare** [comment]
Welcome!
