### ISSUE TITLE
Ready for Release?

### ISSUE THREAD

**Issue by clandaith** [BSData/gates-of-antares#47]
I think it's time to do a big release for the data files.  There has been a lot of work on the files lately.

Thoughts?

**Comment by glasvandrare** [comment]
Sounds good!
Do you want to do it, or should I?

**Comment by glasvandrare** [comment]
Then again, Vescarea has released fairly regularly...

**Comment by clandaith** [comment]
I'm finishing up a vacation. If you want to fire it off that would be great.

**Comment by glasvandrare** [comment]
As in a press release in the FB groups (and other selected places?)

**Comment by shammond42** [comment]
If we want to release we should do it soon. The new book is coming out soon, with new units. If we release when that is out then we just look behind... Or, we wait until we can enter all of those new units.

Are we looking for somebody to write a brief blurb to post?

**Comment by clandaith** [comment]
I think we just do a pull request to test and master.  I'll go ahead and initiate a pull request.
