### ISSUE TITLE
Shared profile errors

### ISSUE THREAD

**Issue by glasvandrare** [BSData/gates-of-antares#52]
Hi!
I'm using the Catalogue Editor, and I keep getting "Characteristic must match a characteristic from the profile type", for what seems to be everything having a Shared Profile. 

Do I need to set something up in my CEditor? Has anyone seen this fault before?
It does not appear with the Algs, probably due to lack of shared profiles.

**Comment by clandaith** [comment]
I've never seen that before.  Can you screenshot the message?  Does it give any other information?  Is it a Java error with a stacktrace?

**Comment by Vescarea** [comment]
Hey I added special rules option the the profiles so they appear directly on the model profile. which will need to be filled in it makes seeing what special rules that init jas easier.

Get Outlook for Android

On Mon, May 16, 2016 at 9:18 AM -0700, "clandaith" notifications@github.com wrote:

I've never seen that before.  Can you screenshot the message?  Does it give any other information?  Is it a Java error with a stacktrace?

---

**Comment by shammond42** [comment]
It sounds similar to the category id's issue I had saving the boromite catalog file -- but that is really just a guess. I had to edit those id's in the XML file directly. Here is the article that clued me in on that. 

https://github.com/BSData/wh40k/issues/131

**Comment by glasvandrare** [comment]
Yea, it's probably something I've missed to add. I've looked at 40k#131 for clues, but not dug too deep into it. 

It is not a Java error, but a Battlescribe one, and seems related to definitions not found in the Catalogue/list currently being edited, but in the Game file. 

How do you guys make sure to have the proper game file loaded while working?

**Comment by Vescarea** [comment]
In the catalogue editor you need to update from the old profile type to the new one as the old one is missing the "Special rules" at the end.

**Comment by glasvandrare** [comment]
Thanks! That sorted it out... Also, I had to clean out my old cache of imported files (Battlescribe though my old stuff had precedence over the new, despite me manually adding the new)
