### ISSUE TITLE
Add FallenHero143 as developer

### ISSUE THREAD

**Issue by glasvandrare** [BSData/gates-of-antares#57]
Could we have FallenHero143 as dev?

**Comment by amis92** [comment]
Ok, I have arequest: can a person who wants to join post such requests themselves? As per [Getting Started wiki](https://github.com/BSData/bsdata/wiki#getting-started)?

In the meantime, @FallenHero143: please accept the invitation in the email or on the [BSData organization webpage](https://github.com/BSData). Welcome aboard!

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide). Cheers!

**Comment by glasvandrare** [comment]
Sure, my mistake. Force of habit from work...

**Comment by amis92** [comment]
Nah, not a mistake. It's a good idea that you approve such requests, so I know you want the person in the team. It just makes organizing things (some aggregation I do) easier for me, when OP is the interested person. :)

**Comment by amis92** [comment]
And also that issue title is uniform through all repos, that way I can filter such requests faster from all issues when going online from time to time. :)
