### ISSUE TITLE
Development branch?

### ISSUE THREAD

**Issue by clandaith** [BSData/gates-of-antares#70]
Do we really need a development branch?  If we're doing pull requests into master, I don't see a need for it.

Thoughts?

**Comment by glasvandrare** [comment]
Could be a good idea for testing and integrating, but branches are cheap; if one is needed, better create it at the time (instead of trying to keep it up to date).

**Comment by clandaith** [comment]
I fully agree.  I say we delete the branch.  Bring it back if needed.
