### ISSUE TITLE
Freeborn - Only "Command Squad" gets special options.

### ISSUE THREAD

**Issue by clandaith** [BSData/gates-of-antares#71]
Reported via Facebook:

Neil Junco Freeborn: command squad is only allowed one option. Rather than one squad may take any options.

**Comment by glasvandrare** [comment]
To continue from Facebook: 
Chase Murphy: Off the top of my head...

The Command Squad was badly messed up.
The Guard Squad point value was 132 instead of 137 as per the Errata.
The House Troops are armed with Mag Guns, not Plasma weaponry.

And all the point costs need to be rechecked for the freeborn I think. There were other errors but I can not recall them.

I'll take a look

**Comment by rythos42** [comment]
I've recently picked up some Freeborn forces and am incentivized to fix this stuff. :)

@glasvandrare I've just finished working on the Freeborn Adventurers list. But I'm wondering -- why does the Freeborn.cat file change when I save the Freeborn_Adventurers.cat? This is troubling, and makes me think there are linkages between the two lists -- there should not be (that I can see). There are notable differences between the lists, even outside of them having different unit options.

**Comment by glasvandrare** [comment]
My guess would be that a few entries are common, but I haven't looked at
the details.

I think the most complex unit is probably the command squad, with all
special rules.
Den 7 jan 2017 01:27 skrev "Craig Fleming" <notifications@github.com>:

**Comment by rythos42** [comment]
But what does "common" mean in Battlescribe? The only common stuff I can see is the Force Entry stuff in the Beyond_the_Gates_of_Antares.gst - everything else is in it's own .cat file. Do you know how the Freeborn_Adventurers.cat would write to the Freeborn.cat when I save it?

**Comment by glasvandrare** [comment]
I haven't looked at it in detail, but I imagine it to be possible to point
to entries in other files by referencing those entries 'unique id', i.e
reference ID that each entry get, that you can use within a file too.
I'll see if I can't analyze the files tomorrow and see if I can verify
that.

**Comment by clandaith** [comment]
This is fixed.
