### ISSUE TITLE
Add New Boromite Units from Xilos Supplement

### ISSUE THREAD

**Issue by shammond42** [BSData/gates-of-antares#73]
Add the following new units:
- Boromite Guildess Arran Gestalin

**Comment by clandaith** [comment]
WooHoo!  Steven, thanks for the input.

**Comment by shammond42** [comment]
I can't seem to assign this story to myself. I have got it.

**Comment by shammond42** [comment]
Ugh, so it looks like the Boromite character Arran Gestalin is the first unit that has multiple categories. She can substitute for a Rock Father (a tactical unit) or a Rock Rider Overseer Squad (a support unit).

I am just learning how to work with BattleScribe list editing. Any thoughts on how best to handle this?

**Comment by shammond42** [comment]
Per this discussion (https://www.facebook.com/groups/gatesofantares/permalink/1172109589487781/) I am going to treat the "and" as a mistake and say that she can only be one category or the other.

Still looking for advice on how to approach this in BattleScribe.
