### ISSUE TITLE
Add New Ghar Units from the Xilos Supplement

### ISSUE THREAD

**Issue by shammond42** [BSData/gates-of-antares#77]
Add the following units:
- Ghar High Commander Karg

**Comment by clandaith** [comment]
This still needs to be added.

**Comment by Harkan38** [comment]
This is on the next batch of work being done

**Comment by TimCoraxAudio** [comment]
@Harkan38 Any update on this?

**Comment by TimCoraxAudio** [comment]
Just looked and it actually seems that this has been added at some point but wasn't closed. Closing issue now as no longer needed

**Comment by TimCoraxAudio** [comment]
Just looked and it actually seems that this has been added at some point but wasn't closed. Closing issue now as no longer needed
