### ISSUE TITLE
Add the Freeborn Adventurers Army from the Xilos Supplement

### ISSUE THREAD

**Issue by shammond42** [BSData/gates-of-antares#80]
Add the new army from the Xilos Supplement. It does not have any new units. Ideally it can share entries with the existing Freeborn army list.

**Comment by Tvayumat** [comment]
New to editing BS files, but I did this today for myself, and then started looking into how to participate in updating armies here.

I created force selector entries for them, and swapped out the invalid units from the original Freeborn, then added in the details for the C3D1 the Adventurers can take.
