### ISSUE TITLE
Isorians?

### ISSUE THREAD

**Issue by clandaith** [BSData/gates-of-antares#82]
Is anyone working on the Isorians?  If not, then I'll go ahead and start.

**Comment by glasvandrare** [comment]
No, please go right ahead!

**Comment by OldLongy** [comment]
Done one.  https://1drv.ms/f/s!Al29kD06hfQMg410SXHFnXSGweGy5A

**Comment by glasvandrare** [comment]
Thanks! I've added it to the development branch, and will test it out a bit before delivery.
Just one small comment; please save the files as .cat instead of .catz (it seems that Appspot, where everyone fetches the files from, hangs if publishing .catz)

**Comment by coruptcopy** [comment]
Fixed an issue with Acc values for Phase Troopers vs Command Squad Phase Troopers. Also added in a bunch of rules. Don't know if you all are doing that or not, but I did it. If you don't want the rules added, the only real issue I saw (and I spent hours) was that the Phase Troopers were listed as Acc 6 when only the ones in the Command Squad have Acc 6. The regular ones are only Acc 5. Nice work, OldLongy!

Here's my dropbox link to my rules addition and single correction: https://www.dropbox.com/s/waen0jztifajrxq/Isorian%20editted.cat?dl=0

**Comment by OldLongy** [comment]
All good matey,  did this for a friend so happy for everyone to dive on it and make it right

**Comment by coruptcopy** [comment]
Also fixed Bikes so that they are Tactical option, not support. Just noticed that. :-p

**Comment by coruptcopy** [comment]
Thanks for doing all the hard work, OldLongy! I was gearing up to start on this myself, as I just started playing Isorians. I really appreciate it.

**Comment by glasvandrare** [comment]
Great job! 
I'll add it and make a delivery today or tomorrow.
