### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by Tvayumat** [BSData/gates-of-antares#83]
I've been updated the Gates of Antares datafiles extensively for my own use, and I'd like to be able to upload them for public use.

**Comment by amis92** [comment]
Hello, @Tvayumat. Please accept the invitation in the email or on the [BSData organization webpage](https://github.com/BSData). Welcome aboard!

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

Also this repo is currently mostly maintained by @clandaith and @glasvandrare. Get in touch with them before doing big changes.

Cheers!
