### ISSUE TITLE
BattleScribe 2.0

### ISSUE THREAD

**Issue by Jonskichov** [BSData/gates-of-antares#91]
Hi guys.

BattleScribe 2.0 is coming and it contains some major changes to Data Editor and the data format.

While it should happily upgrade 1.15.x format data files to the new format, you never know what sneaky bugs might be lurking...

It would help a lot if you could run your data through it and make sure nothing gets broken so we have no nasty surprises on release day (whenever that might be...).

**Alpha Downloads:**
Desktop: https://github.com/BattleScribe/Desktop-Alphas/issues/1
Android: https://github.com/BattleScribe/Android-Alphas/issues/1
iOS: https://github.com/BattleScribe/iOS-Alphas/issues/1

If you find any issues, please do let me know: https://github.com/BattleScribe/Desktop-Alphas/issues

**Comment by glasvandrare** [comment]
@Jonskichov: Great, I'll look into it (now that I'm back from holiday).
Meanwhile, it seems that we have a release issue, Appspot is not picking up the latest release, for some reason. Would it be possible for you to look into the logs and see why?

**Comment by Jonskichov** [comment]
Looks like you sorted it out :)

Appspot doesn't like the zipped versions of the files.

Hope you like the new Data Editor :)
