### ISSUE TITLE
Rebel Ghar Force

### ISSUE THREAD

**Issue by Mayegelt** [BSData/gates-of-antares#92]
Made this one in the last few hours, seems to work, not sure if there are any errors, and kinda need to fill out a load of rules what are linked up.

https://drive.google.com/open?id=0B2WSzVPkudYKWHNHbDk3LXl5STA

Could also use a bit of tidying up probably. Was my first go at it.

Only 2 probs i know of are that of course it doesn't know the force organisation chart thing for how many tacts and stuff it needs. Also it doesn't know how to deal with what are limited choices. Though all Limited choices I think I put a flag on for the "Limited" rule and also made the Leader of each of the units a "Limited" rather than just a "Model"

**Comment by Mayegelt** [comment]
Seems like in BattleScribe 2.0 there is an issue on some costs. But they can be sorted out i think later.

**Comment by glasvandrare** [comment]
Thanks! I've added it to the development branch, and will test it out a bit before delivery.
Just one small comment; please save the files as .cat instead of .catz (it seems that Appspot, where everyone fetches the files from, hangs if publishing .catz)

**Comment by glasvandrare** [comment]
Merged and released
