### ISSUE TITLE
Added 2 updated files and 1 new one

### ISSUE THREAD

**Issue by Mayegelt** [BSData/gates-of-antares#94]
Page 83 BfX book allows loads of squads to get Sync drones. Added them on to Boromite and Algoryn. Also put up Rebel Ghar :)
See my pull request for details.
If it gets done, then i will work on Boromite Clan, Freeboes, and Concord, and add the new one to Ghar :)

**Comment by glasvandrare** [comment]
Great!
I'll merge and review later tonight!
